# Shell variables
# Generated by 'wal'
wallpaper='/home/nya/Pictures/.wallpaper/wall.jpg'

# Special
background='#02030F'
foreground='#d8b5ca'
cursor='#d8b5ca'

# Colors
color0='#02030F'
color1='#534B6C'
color2='#EE9464'
color3='#245498'
color4='#5F6193'
color5='#8C748B'
color6='#976F9F'
color7='#d8b5ca'
color8='#977e8d'
color9='#534B6C'
color10='#EE9464'
color11='#245498'
color12='#5F6193'
color13='#8C748B'
color14='#976F9F'
color15='#d8b5ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
